/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "szjbwhwyswssjbrpihbm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6amJ3aHd5c3dzc2picnBpaGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0NzMzMDcsImV4cCI6MjA4MjA0OTMwN30.D9kR5-0f8fYn1kYDy91ox1QW0XPPQA7FDgJ-FLUqb40"